name: Build, Package and Release

on:
  release:
    types: [created]

jobs:
  build-linux:
    uses: ./.github/workflows/package-linux.yml

  build-windows:
    uses: ./.github/workflows/package-windows.yml

  create-release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write # Add this permission block
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release $${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Linux Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/dist/shady-search-linux-${{ env.VERSION }}
          asset_name: shady-search-linux-${{ env.VERSION }}
          asset_content_type: application/zip

      - name: Upload Windows Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/dist/shady-search-windows-${{ env.VERSION }}
          asset_name: shady-search-windows-${{ env.VERSION }}
          asset_content_type: application/zip