name: Build, Package and Upload Linux and Windows distributions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    uses: ./.github/workflows/package-linux.yml

  build-windows:
    uses: ./.github/workflows/package-windows.yml