name: Build, Package and Release

on:
  release:
    types: [created]

jobs:
  build-linux:
    uses: ./.github/workflows/package-linux.yml

  build-windows:
    uses: ./.github/workflows/package-windows.yml

  upload-assets:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload Linux Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/shady-search-linux-${{ env.VERSION }}
          asset_name: shady-search-linux-${{ env.VERSION }}
          asset_content_type: application/zip

      - name: Upload Windows Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/shady-search-windows-${{ env.VERSION }}
          asset_name: shady-search-windows-${{ env.VERSION }}
          asset_content_type: application/zip