name: Build and Package Linux Distribution

on:
  workflow_call:

jobs:
  package-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Azul Zulu JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and package
        run: ./gradlew clean jpackage -i

      - name: Get Gradle version (Linux, must be run after jpackage)
        id: get_version
        run: echo "VERSION=$(./gradlew printVersion -q| tr -d '[:space:]')" >> $GITHUB_ENV

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: shady-search-linux-${{ env.VERSION }}
          path: build/dist