name: Release Packages

on:
  release:
    types: [created]

jobs:
  build-linux:
    uses: ./.github/workflows/package-linux.yml

  build-windows:
    uses: ./.github/workflows/package-windows.yml

  upload-assets:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get release version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: ls -R artifacts
        shell: bash

      - name: Upload Linux Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/shady-search-linux-${{ env.VERSION }}/*.deb
          asset_name: shady-search-linux-${{ env.VERSION }}.deb
          asset_content_type: application/x-debian-package

      - name: Upload Windows Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/shady-search-windows-${{ env.VERSION }}/*.msi
          asset_name: shady-search-windows-${{ env.VERSION }}.msi
          asset_content_type: application/x-msi

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update version for next development
        run: |
          # Increment patch version
          NEXT_VERSION=$(echo ${{ env.VERSION }} | awk -F. '{$NF+=1;}1' OFS=.)
          # Update the file with SNAPSHOT suffix
          sed -i "s/version=.*/version=$NEXT_VERSION-SNAPSHOT/" gradle.properties

          git add gradle.properties
          git commit -m "Bump version to $NEXT_VERSION-SNAPSHOT"
          git push origin main