name: Release Packages

on:
  release:
    types: [created]

jobs:
  build-linux:
    uses: ./.github/workflows/package-linux.yml

  build-windows:
    uses: ./.github/workflows/package-windows.yml

  upload-assets:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version
        run: echo "VERSION=$(./gradlew printVersion -q)" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Extract artifacts
        run: |
          cd artifacts
          unzip "shady-search-linux-${{ env.VERSION }}.zip"
          unzip "shady-search-windows-${{ env.VERSION }}.zip"

      - name: Upload Linux Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/*.deb
          asset_name: shady-search-linux-${{ env.VERSION }}.deb
          asset_content_type: application/x-debian-package

      - name: Upload Windows Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/*.msi
          asset_name: shady-search-windows-${{ env.VERSION }}.msi
          asset_content_type: application/x-msi